eval "$(/opt/homebrew/bin/brew shellenv)"

if [ -d ~/.local/bin ]; then
    export PATH=~/.local/bin:$PATH
fi

# https://linuxhint.com/configure-use-aliases-zsh/
alias ll="ls -l"
alias la="ls -la"
alias lvim="$HOME/.local/bin/lvim"

# Dotfiles exports
export DOTDIR=$HOME/dotfiles
export HELPER=$DOTDIR/tools/helpers

# Golang Exports
export GOROOT="$(brew --prefix golang)/libexec"
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"

# Nordic Tools
export NRFUTILS="$HOME/.nrfutil/bin"

export PATH=$PATH:$GOROOT:$GOPATH:$GOBIN:$HELPERS:$NRFUTILS

export GPG_TTY=$(tty)

# NPM and NVM exports 
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# Oh-my-zsh export
export ZSH="/Users/brendon.lecomte/.oh-my-zsh"
# plugins=(git zsh-syntax-highlighting zsh-autosuggestions)
# source $ZSH/oh-my-zsh.sh


# allows calling python/pip rather than python3/pip3 
export PATH="/opt/homebrew/opt/python/libexec/bin:$PATH"
